### ISSUE TITLE
Deploy button does not work with setup function

### ISSUE THREAD

**Issue by Mandur** [loriot/AzureSolutionTemplate#26]
Introduced in #22 
Seems to be a powershell version issue

**Comment by Mandur** [comment]
fixed by #27

**Comment by anraman** [comment]
This is the error you get: 

> Unable to download deployment content from 'https://blah.azurewebsites.net/api/setup' ... Code: InvalidContentLink

**Comment by anraman** [comment]
It's caused by the fact that the deploy button calls ```New-AzureRmResourceGroupDeployment``` (old CLI version) rather than ``` az group deployment create``` (which works)

**Comment by Mandur** [comment]
Corrected moving Microsoft.Resources/deployments version to  2014-04-01-preview
