### ISSUE TITLE
Make LORIOT variables optional in the ARM template

### ISSUE THREAD

**Issue by vjrantal** [loriot/AzureSolutionTemplate#4]
It is useful to support deploying everything without the LORIOT connection to test the pipeline from IoT Hub onwards.

This task includes updating the ARM template to have some values optional and also code updates to fail gracefully in case LORIOT-related environment variables are not set.

**Comment by cpiock** [comment]
@vjrantal what I should change in the arm template? code now is handling empty loriot configs

**Comment by vjrantal** [comment]
@cpiock The simplest thing you could do for starters is to provide empty string as default value so add something like:

```
diff --git a/azuredeploy.json b/azuredeploy.json
index 831e88d..9d39ec0 100644
--- a/azuredeploy.json
+++ b/azuredeploy.json
@@ -10,6 +10,7 @@
         },
         "loriotAppId": {
             "type": "string",
+            "defaultValue": "",
             "metadata": {
                 "description": "The LORIOT App Id that can be found in the LORIOT portal."
             }
```

Looks like the deploy.azure.com site doesn't show the descriptions from the template so we'd have to see where we should document that these are optional and what the outcome is when leaving empty.
